/*export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";
export const FETCH_ARTICLES_CLEARE = "FETCH_ARTICLES_CLEARE";

export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILUR";
export const FETCH_ARTICLE_CLEARE = "FETCH_ARTICLE_CLEARE";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLES_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLES_SUCCESS";
export const EDIT_ARTICLE_FAILURE = "EDIT_ARTICLES_FAILURE";
export const EDIT_ARTICLE_CLEARE = "EDIT_ARTICLES_CLEARE";

export const REMOVE_ARTICLE_REQUEST = "REMOVE_ARTICLES_REQUEST";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLES_SUCCES";
export const REMOVE_ARTICLE_FAILURE = "REMOVE_ARTICLES_FAILURE";
export const REMOVE_ARTICLE_CLEARE = "REMOVE_ARTICLES_CLEARE";

export const ADD_ARTICLE_REQUEST = "ADD_ARTICLES_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLES_SUCCES";
export const ADD_ARTICLE_FAILURE = "ADD_ARTICLES_FAILURE";
export const ADD_ARTICLE_CLEARE = "ADD_ARTICLES_CLEARE";*/
